version: "3"
services:
  hapi-fhir-jpaserver-start:
    build: .
    #container_name: hapi-fhir-jpaserver-start
    container_name: beapen/fhir-phis-dw
    restart: on-failure
    ports:
      - "8092:8080"
  hapi-fhir-mysql:
    image: mysql:latest
    container_name: hapi-fhir-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'hapi'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    #volumes:
      #- hapi-fhir-mysql:/var/lib/mysql
  # https://alysivji.github.io/elasticsearch-kibana-with-docker-compose.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    ports:
      - "8093:5601"
#volumes:
  #hapi-fhir-mysql: